[package]
name = "streamlet"
version = "0.1.0"
authors = ["Romain Leroux <romain@leroux.dev>"]
edition = "2018"

[dependencies]
clipboard = "0.5"
gstreamer = "0.16"
gstreamer-player = "0.16"
serde_json = "1"
subprocess = "0.2"
termion = "1.5"
tui = "0.12"
unicode-width = "0.1"
